#!/usr/bin/env python3
"""sample_100 JSON 번들을 Spring MariaDB용 멱등 시드 SQL로 변환한다."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Iterable


def sql_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace("'", "''")
        .replace("\0", "\\0")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )
    return f"'{escaped}'"


def json_string(value: Any) -> str:
    return sql_string(json.dumps(value, ensure_ascii=False, separators=(",", ":")))


def chunks(values: list[str], size: int = 50) -> Iterable[list[str]]:
    for start in range(0, len(values), size):
        yield values[start : start + size]


def brand_name(product: dict[str, Any]) -> str:
    value = product.get("attributes", {}).get("브랜드")
    if isinstance(value, str) and value.strip() and value.strip() != "기타":
        return value.strip()[:100]
    return f"11번가 판매자 {product['seller_no']}"[:100]


def option_name(item: dict[str, Any]) -> str:
    value = str(item.get("label") or item.get("value") or "기본 옵션").strip()
    return value[:100] or "기본 옵션"


def load_bundle(source: Path) -> tuple[list[dict[str, Any]], dict[int, dict[str, Any]], dict]:
    products = [json.loads(path.read_text()) for path in source.glob("products/*.json")]
    products.sort(key=lambda item: int(item["product_id"]))
    documents = {
        int(row["product_id"]): row
        for line in (source / "ai/documents.jsonl").read_text().splitlines()
        if line.strip()
        for row in [json.loads(line)]
    }
    schemas = json.loads((source / "category_schemas.json").read_text())

    product_ids = {int(item["product_id"]) for item in products}
    if len(products) != 100 or len(product_ids) != 100:
        raise ValueError(f"상품은 중복 없이 100건이어야 합니다: {len(products)}건")
    if set(documents) != product_ids:
        raise ValueError("products JSON과 ai/documents.jsonl의 product_id 집합이 다릅니다")
    missing_schemas = sorted({row["category"] for row in documents.values()} - set(schemas))
    if missing_schemas:
        raise ValueError(f"category schema 누락: {missing_schemas}")
    return products, documents, schemas


def render(source: Path) -> str:
    products, documents, schemas = load_bundle(source)
    domains = sorted({item["domain"] for item in products})
    categories = sorted(
        {
            (item["domain"], documents[int(item["product_id"])]["category"])
            for item in products
        }
    )
    brands = sorted({brand_name(item) for item in products})

    lines = [
        "-- AUTO-GENERATED by scripts/generate-sample-100-sql.py; 직접 수정하지 마세요.",
        "-- source: ../sample_100 (11번가 층화 샘플 100건)",
        "-- 기존 Phase 2/6 데모 데이터는 유지하고 원본 product_id로 100건을 추가/upsert합니다.",
        "SET NAMES utf8mb4;",
        "START TRANSACTION;",
        "",
        "-- 13개 도메인 대분류",
    ]
    for domain in domains:
        q = sql_string(domain)
        lines.extend(
            [
                "INSERT INTO category (parent_id, name, attribute_schema, created_at, updated_at)",
                f"VALUES (NULL, {q}, NULL, NOW(), NOW())",
                "ON DUPLICATE KEY UPDATE updated_at = VALUES(updated_at);",
            ]
        )

    lines.extend(["", "-- 87개 AI 카테고리 소분류 + 속성 키 soft schema"])
    for domain, category in categories:
        attr_keys = [entry["attr_key"] for entry in schemas[category]]
        lines.extend(
            [
                "INSERT INTO category (parent_id, name, attribute_schema, created_at, updated_at)",
                "VALUES ("
                f"(SELECT id FROM category WHERE name = {sql_string(domain)} LIMIT 1), "
                f"{sql_string(category)}, {json_string(attr_keys)}, NOW(), NOW())",
                "ON DUPLICATE KEY UPDATE parent_id = VALUES(parent_id), "
                "attribute_schema = VALUES(attribute_schema), updated_at = VALUES(updated_at);",
            ]
        )

    lines.extend(["", "-- 크롤링 브랜드(판매자 계정 미연결)"])
    brand_values = [
        f"(NULL, {sql_string(name)}, NULL, '11번가 sample_100 크롤링 브랜드', NOW(), NOW())"
        for name in brands
    ]
    for group in chunks(brand_values):
        lines.extend(
            [
                "INSERT INTO brand (seller_id, name, logo_url, description, created_at, updated_at) VALUES",
                ",\n".join(group),
                "ON DUPLICATE KEY UPDATE description = VALUES(description), updated_at = VALUES(updated_at);",
            ]
        )

    product_values: list[str] = []
    for product in products:
        product_id = int(product["product_id"])
        doc = documents[product_id]
        price = int(product["price"])
        original_price = max(price, int(product["list_price"]))
        summary = product["search_doc"][:500]
        product_values.append(
            "(" + ", ".join(
                [
                    str(product_id),
                    f"(SELECT id FROM brand WHERE name = {sql_string(brand_name(product))} LIMIT 1)",
                    f"(SELECT id FROM category WHERE name = {sql_string(doc['category'])} LIMIT 1)",
                    sql_string(product["title"][:200]),
                    str(original_price),
                    str(price),
                    "100",
                    sql_string(product["main_image"][:500]),
                    "0",
                    sql_string(summary),
                    json_string(product["attributes"]),
                    sql_string(product["search_doc"]),
                    "'ON_SALE'",
                    "NOW()",
                    "NOW()",
                ]
            ) + ")"
        )

    lines.extend(["", "-- 상품 100건: AI pg-catalog와 동일한 원본 product_id 사용"])
    for group in chunks(product_values, 25):
        lines.extend(
            [
                "INSERT INTO product (id, brand_id, category_id, name, original_price, price, stock_quantity,",
                "                     image_url, base_sales_count, summary, attributes, description, status,",
                "                     created_at, updated_at) VALUES",
                ",\n".join(group),
                "ON DUPLICATE KEY UPDATE brand_id = VALUES(brand_id), category_id = VALUES(category_id),",
                "name = VALUES(name), original_price = VALUES(original_price), price = VALUES(price),",
                "stock_quantity = VALUES(stock_quantity), image_url = VALUES(image_url),",
                "summary = VALUES(summary), attributes = VALUES(attributes), description = VALUES(description),",
                "status = VALUES(status), updated_at = VALUES(updated_at);",
            ]
        )

    ids = ",".join(str(int(item["product_id"])) for item in products)
    lines.extend(["", "-- 재실행 시 샘플 상품 옵션만 원본 상태로 교체", f"DELETE FROM product_option WHERE product_id IN ({ids});"])
    option_values: list[str] = []
    for product in products:
        product_id = int(product["product_id"])
        for item in product.get("options", {}).get("items") or []:
            option_values.append(
                f"({product_id}, {sql_string(option_name(item))}, {int(item.get('add_price') or 0)}, NOW(), NOW())"
            )
    for group in chunks(option_values):
        lines.extend(
            [
                "INSERT INTO product_option (product_id, name, extra_price, created_at, updated_at) VALUES",
                ",\n".join(group) + ";",
            ]
        )

    lines.extend(
        [
            "",
            "COMMIT;",
            "",
            "-- 적재 확인",
            f"SELECT COUNT(*) AS sample_product_count FROM product WHERE id IN ({ids});",
            f"SELECT COUNT(*) AS sample_option_count FROM product_option WHERE product_id IN ({ids});",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    workspace = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=workspace / "sample_100")
    parser.add_argument(
        "--output", type=Path, default=Path(__file__).resolve().parent / "seed-sample-100.sql"
    )
    args = parser.parse_args()
    sql = render(args.source.resolve())
    args.output.write_text(sql)
    print(f"generated {args.output}: {sql.count(chr(10)) + 1} lines")


if __name__ == "__main__":
    main()
